const sections=[['intro','Accueil'],['coding','Coding'],['react','React / TS'],['backend','Django / SQL'],['codebase','Codebase Review'],['system','System Design'],['incident','Production Incident'],['ai','AI Engineering'],['gis','GIS'],['communication','Senior Communication'],['english','English'],['final','Bilan']];
const durations={coding:1800,react:2100,backend:2700,codebase:2700,system:3600,incident:1800,ai:2400,gis:1200,communication:1200,english:900};
let state={};try{state=JSON.parse(localStorage.getItem('senior-mission-2027-diag')||'{}')}catch(e){}
state.completed=state.completed||{};state.timers=state.timers||{};state.autoScores=state.autoScores||{};
let current='intro',interval=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function persist(){localStorage.setItem('senior-mission-2027-diag',JSON.stringify(state));$('#save-state').textContent='sauvé';setTimeout(()=>$('#save-state').textContent='local',700);progress()}
function bindFields(){$$('[data-key]').forEach(el=>{const k=el.dataset.key;if(state[k]!=null&&!el.classList.contains('preset'))el.value=state[k];if(state[k]!=null&&el.classList.contains('preset'))el.value=state[k];else if(el.classList.contains('preset')&&state[k]==null)state[k]=el.value;el.addEventListener('input',()=>{state[k]=el.value;persist()})})}
function renderNav(){const nav=$('#nav');nav.innerHTML='';sections.forEach(([id,label])=>{const b=document.createElement('button');b.textContent=label;if(id===current)b.classList.add('active');if(state.completed[id])b.classList.add('done');b.onclick=()=>go(id);nav.appendChild(b)})}
function go(id){current=id;$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.id===id));renderNav();window.scrollTo({top:0,behavior:'smooth'});startTimer(id);if(id==='final')scorecard()}
function complete(id,next){state.completed[id]=true;persist();go(next)}
function progress(){const ids=sections.slice(1,-1).map(x=>x[0]),done=ids.filter(id=>state.completed[id]).length,p=Math.round(done/ids.length*100);$('#bar').style.width=p+'%';$('#pct').textContent=p+'%';renderNav()}
function startTimer(id){if(interval)clearInterval(interval);if(!durations[id])return;if(state.timers[id]==null)state.timers[id]=durations[id];const el=document.querySelector('[data-timer="'+id+'"]');const tick=()=>{const s=Math.max(0,state.timers[id]||0),m=Math.floor(s/60),ss=s%60;el.textContent=String(m).padStart(2,'0')+':'+String(ss).padStart(2,'0');el.style.color=s<300?'var(--red)':'';if(s>0){state.timers[id]=s-1;if(s%10===0)persist()}};tick();interval=setInterval(tick,1000)}
function exportJSON(){state.exportedAt=new Date().toISOString();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='senior-mission-2027-diagnostic.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function copySummary(){let t='SENIOR MISSION 2027 — DIAGNOSTIC\n\n';Object.keys(state).filter(k=>!['completed','timers','autoScores','exportedAt'].includes(k)).forEach(k=>t+='## '+k+'\n'+state[k]+'\n\n');navigator.clipboard.writeText(t).then(()=>alert('Résumé copié.'))}
function reset(){if(confirm('Effacer toutes les réponses et temps ?')){localStorage.removeItem('senior-mission-2027-diag');location.reload()}}
function scorecard(){const items=['Coding','React / TS','Django / SQL','Codebase Review','System Design','Production','AI Judgment','GIS','Senior Communication','English'],box=$('#scorecard');box.innerHTML='<div><b>Domaine</b></div><div><b>Niveau</b></div><div><b>Confiance</b></div>';items.forEach((name,i)=>{const k='s'+i,c='c'+i,a=document.createElement('div');a.textContent=name;const b=document.createElement('div'),sel=document.createElement('select');['🔴','🟠','🟢'].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;if(state.autoScores[k]===v)o.selected=true;sel.appendChild(o)});sel.onchange=()=>{state.autoScores[k]=sel.value;persist()};b.appendChild(sel);const d=document.createElement('div'),cs=document.createElement('select');['Faible','Moyenne','Haute'].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;if(state.autoScores[c]===v)o.selected=true;cs.appendChild(o)});cs.onchange=()=>{state.autoScores[c]=cs.value;persist()};d.appendChild(cs);box.append(a,b,d)})}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('.complete').forEach(b=>b.onclick=()=>complete(b.dataset.complete,b.dataset.next));$$('[data-reveal]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.reveal).classList.add('show'));
$('#export-side').onclick=exportJSON;$('#export-final').onclick=exportJSON;$('#copy-summary').onclick=copySummary;$('#reset').onclick=reset;
bindFields();renderNav();progress();